/**
 * Writes public/robots.txt and public/sitemap.xml.
 *
 * The product list is read out of `src/data/products.ts` rather than typed
 * here, because the catalogue moves — `npm run catalog:fetch` rewrites it from
 * Supabase whenever the client publishes something in /admin. A hand-written
 * sitemap would be stale the first time they added a door.
 *
 * Wired into `npm run build`, so a deploy can never ship a sitemap describing
 * the previous catalogue.
 *
 * ⚠️ Deliberately excluded: /checkout, /order-confirmed (both are states of one
 * person's session, not pages anyone should land on cold), /dev/gallery (DEV
 * only) and /admin (auth-gated, and robots.txt disallows it outright).
 * /door/:id is excluded too — it is the legacy redirect, and listing a URL that
 * 301s is asking a crawler to spend its budget learning that.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { createServer } from 'vite'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** The origin the site is served from. Change here and both files follow. */
const ORIGIN = 'https://patidartimbers.com'

/** Static routes, in the order the nav presents them. */
const STATIC = ['/', '/timbers', '/doors', '/ply', '/wpc', '/shop', '/visit', '/faq', '/policies']

/*
 * The real `PRODUCTS`, evaluated — not a regex over the source.
 *
 * The catalogue is a *merge*: local products in products.ts, CMS products in
 * catalog.gen.ts overriding by id, plus brand-new CMS slugs appended, and then
 * a price overlay on top. Scraping `id:` out of one file misses most of it and
 * re-implementing the merge here would be a second copy of a rule that has
 * already moved twice. Vite is already a dependency and loads the TypeScript
 * directly, so the sitemap lists exactly what the site routes.
 */
const server = await createServer({ root, logLevel: 'error', server: { middlewareMode: true } })
let ids
try {
  const mod = await server.ssrLoadModule('/src/data/products.ts')
  ids = mod.PRODUCTS.map((p) => p.id)
} finally {
  await server.close()
}
if (!ids?.length) throw new Error('no products loaded from src/data/products.ts')

const today = new Date().toISOString().slice(0, 10)
const urls = [
  ...STATIC.map((path) => ({ path, priority: path === '/' ? '1.0' : '0.8' })),
  ...ids.map((id) => ({ path: `/product/${id}`, priority: '0.6' })),
]

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    ({ path, priority }) =>
      `  <url>\n    <loc>${ORIGIN}${path}</loc>\n    <lastmod>${today}</lastmod>\n    <priority>${priority}</priority>\n  </url>`,
  )
  .join('\n')}
</urlset>
`

const robots = `# Patidar Doors — generated by scripts/build-sitemap.mjs, do not hand-edit.
User-agent: *
Allow: /

# The admin is auth-gated anyway; keeping it out of the index keeps the login
# page from turning up in a search for the brand.
Disallow: /admin
# Both are one visitor's session state, not pages to land on.
Disallow: /checkout
Disallow: /order-confirmed

Sitemap: ${ORIGIN}/sitemap.xml
`

writeFileSync(resolve(root, 'public/sitemap.xml'), sitemap)
writeFileSync(resolve(root, 'public/robots.txt'), robots)
console.log(`sitemap.xml: ${urls.length} urls (${STATIC.length} static + ${ids.length} products) · robots.txt written`)
