/* Self-host the two brand faces.
 *
 * Why this exists: the site is client-rendered, so no text exists in the HTML
 * for the browser to match against a @font-face. Loading the faces from
 * fonts.googleapis.com therefore serialised into
 *   html → css2 (a whole round trip to a third origin for 1 kB) → woff2,
 * and the woff2 leg could not even start until React had rendered — measured at
 * 1383 ms on a throttled mid-range phone, with the swap landing at 2820 ms.
 * Every visitor read the hero in Georgia and then watched it reflow.
 *
 * Self-hosted, the faces sit on the same connection as everything else and can
 * be <link rel=preload>ed from the HTML, so they start with the bundle instead
 * of after it.
 *
 * We ship Google's own subsets rather than cutting our own: no fonttools in the
 * pipeline, and staying on their exact unicode-ranges keeps this re-runnable
 * when a face is revved. Run `node scripts/fetch-fonts.mjs` to refresh.
 *
 * Only `latin` and `latin-ext` are kept. latin-ext is not optional — ₹ (U+20B9)
 * lives in its range (U+20AD-20C0), and this is a store that prints prices.
 * The Noto/Sangam tails in global.css still carry Kannada and Devanagari; those
 * ship with the OS and are never downloaded.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

/* A desktop Chrome UA is what makes Google serve woff2; older UAs get ttf. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'

/* Exactly the faces the stylesheet asks for, and nothing else.
   Cormorant carries names (roman 400/500/600) and one italic — `.hero__title em`
   and `.cta__title em`, both set at 500, so italic 400 and 600 were being
   declared and never used. Archivo is variable, so one file per subset covers
   400 through 800 (the 800 is the economics band's big number). */
const QUERY =
  'family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,500' + '&family=Archivo:wght@400..800' + '&display=swap'

const KEEP = new Set(['latin', 'latin-ext'])
const OUT = fileURLToPath(new URL('../public/fonts/', import.meta.url))

const css = await (await fetch(`https://fonts.googleapis.com/css2?${QUERY}`, { headers: { 'User-Agent': UA } })).text()

/* Google emits `/* subset *\/` above each @font-face block. */
const blocks = css
  .split('/*')
  .slice(1)
  .map((chunk) => {
    const subset = chunk.slice(0, chunk.indexOf('*/')).trim()
    const face = chunk.slice(chunk.indexOf('*/') + 2)
    const get = (re) => face.match(re)?.[1]
    return {
      subset,
      family: get(/font-family:\s*'([^']+)'/),
      style: get(/font-style:\s*(\w+)/),
      weight: get(/font-weight:\s*([\d ]+)/)?.trim(),
      url: get(/url\(([^)]+)\)/),
      range: get(/unicode-range:\s*([^;]+);/),
    }
  })
  .filter((b) => b.url && KEEP.has(b.subset))

await mkdir(OUT, { recursive: true })

/* Both faces are variable: Google serves ONE file per (style, subset) and then
   declares it once per requested weight. Writing those out verbatim would emit
   three identical @font-faces for Cormorant at 400/500/600 — and since the last
   one wins, every weight but 600 would have been synthesised from it. Group by
   the file instead and declare a real `font-weight: min max` range, which is
   what lets the browser interpolate the actual axis. */
const groups = new Map()
for (const b of blocks) {
  const key = `${b.family}|${b.style}|${b.subset}`
  const g = groups.get(key) ?? { ...b, weights: [] }
  g.weights.push(...b.weight.split(/\s+/).map(Number))
  groups.set(key, g)
}

let bytes = 0
const faces = []

for (const g of groups.values()) {
  const lo = Math.min(...g.weights)
  const hi = Math.max(...g.weights)
  const slug = `${g.family.toLowerCase().replace(/\s+/g, '-')}-${g.style}-${lo}${hi === lo ? '' : `-${hi}`}-${g.subset}.woff2`
  const buf = Buffer.from(await (await fetch(g.url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  await writeFile(OUT + slug, buf)
  bytes += buf.length
  faces.push({ ...g, file: slug, weight: lo === hi ? `${lo}` : `${lo} ${hi}` })
  console.log(`  ${String(Math.round(buf.length / 1024)).padStart(4)} kB  ${slug}  (weight ${lo === hi ? lo : `${lo}–${hi}`})`)
}

const css_ = faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('/fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
  )
  .join('\n\n')

await writeFile(
  fileURLToPath(new URL('../src/styles/fonts.css', import.meta.url)),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n   Faces are self-hosted so they can be preloaded from index.html; see the\n   script's header for why the Google-hosted version could not be. */\n\n${css_}\n`,
)

console.log(`\n${faces.length} files, ${Math.round(bytes / 1024)} kB → public/fonts/`)
console.log('latin subsets to preload in index.html:')
for (const f of faces.filter((x) => x.subset === 'latin')) console.log(`  /fonts/${f.file}`)
