/**
 * Pull the published catalogue from Sanity into the site bundle.
 *
 * Reads SANITY_PROJECT_ID / SANITY_DATASET (and optional SANITY_READ_TOKEN for
 * private datasets) from the environment or a root `.env` file, queries the
 * public CDN API, converts documents to the site's Product shape, and writes
 * src/data/catalog.gen.ts. With no project configured it writes an empty
 * catalog and exits 0 — the site then runs purely on the local data files.
 *
 * Run: npm run cms:fetch   (Vercel build: `npm run cms:fetch && npm run build`)
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT = path.join(ROOT, 'src/data/catalog.gen.ts')
const API_VERSION = 'v2025-02-19'

async function loadEnv() {
  try {
    const raw = await readFile(path.join(ROOT, '.env'), 'utf8')
    for (const line of raw.split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
      if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
    }
  } catch {
    // no .env — fine
  }
}

function emptyCatalog(reason) {
  return `/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * ${reason}
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = []
`
}

/** Sanity image URL → responsive ProductImage (CDN handles resize/webp). */
function toImage(img, alt) {
  if (!img?.url || !img.w || !img.h) return undefined
  const v = (w) => `${img.url}?w=${w}&fm=webp&q=75`
  return { src: v(480), srcSet: `${v(480)} 480w, ${v(960)} 960w`, alt, w: img.w, h: img.h }
}

function toVisual(doc) {
  const cover = toImage(doc.cover, doc.name)
  if (cover) {
    const gallery = (doc.gallery ?? []).map((g) => toImage(g, doc.name)).filter(Boolean)
    return { kind: 'photo', cover, gallery }
  }
  const s = doc.swatch
  if (s?.material && s.base && s.dark && s.light) {
    return { kind: 'material', material: s.material, base: s.base, dark: s.dark, light: s.light }
  }
  // no photo, no swatch — neutral door placeholder
  return { kind: 'art', art: 'classic', tones: 'wood', defaultTone: 'teak' }
}

await loadEnv()
const projectId = process.env.SANITY_PROJECT_ID
const dataset = process.env.SANITY_DATASET || 'production'

if (!projectId) {
  await writeFile(OUT, emptyCatalog('No SANITY_PROJECT_ID configured — site uses local data only.'))
  console.log('cms:fetch — no SANITY_PROJECT_ID; wrote empty catalog (local data only)')
  process.exit(0)
}

const query = /* groq */ `*[_type == "product" && defined(slug.current)] | order(world asc, sub asc, order asc, name asc) {
  "id": slug.current, name, world, sub, tag, story, specs, purchasable, price, priceUnit, order,
  "cover": cover{ "url": asset->url, "w": asset->metadata.dimensions.width, "h": asset->metadata.dimensions.height },
  "gallery": gallery[]{ "url": asset->url, "w": asset->metadata.dimensions.width, "h": asset->metadata.dimensions.height },
  swatch
}`

const url = `https://${projectId}.apicdn.sanity.io/${API_VERSION}/data/query/${dataset}?query=${encodeURIComponent(query)}&perspective=published`
const headers = process.env.SANITY_READ_TOKEN ? { Authorization: `Bearer ${process.env.SANITY_READ_TOKEN}` } : {}
const res = await fetch(url, { headers })
if (!res.ok) {
  console.error(`cms:fetch failed: ${res.status} ${await res.text()}`)
  process.exit(1)
}
const { result } = await res.json()

const products = result
  .filter((d) => d.id && d.name && d.world && d.sub && d.tag)
  .map((d) => ({
    id: d.id,
    name: d.name,
    world: d.world,
    sub: d.sub,
    tag: d.tag,
    ...(d.story ? { story: d.story } : {}),
    specs: d.specs ?? [],
    visual: toVisual(d),
    purchasable: Boolean(d.purchasable && d.price),
    ...(d.price ? { price: d.price } : {}),
    ...(d.priceUnit ? { priceUnit: d.priceUnit } : {}),
  }))

const ts = `/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * Fetched from Sanity project ${projectId}/${dataset} at ${new Date().toISOString()}.
 * CMS products override local ones by id (except Designer Studio) and new
 * slugs are appended — see the merge in products.ts.
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)}
`
await writeFile(OUT, ts)
console.log(`cms:fetch — wrote ${products.length} products from ${projectId}/${dataset}`)
