/**
 * Pull the published catalogue from Supabase into the site bundle.
 *
 * Reads VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY from the environment or a
 * root `.env`, queries the public PostgREST API, converts rows to the site's
 * Product shape, and writes src/data/catalog.gen.ts. With no project
 * configured it writes an empty catalog and exits 0 — the site then runs on
 * the local data files alone.
 *
 * Run: npm run catalog:fetch   (Vercel build: `npm run catalog:fetch && npm run build`)
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT = path.join(ROOT, 'src/data/catalog.gen.ts')

// Default material swatch per world, for products with no photo yet.
const MATERIAL = {
  timbers: { kind: 'material', material: 'timber', base: '#8A6845', dark: '#6E5236', light: '#A57F55' },
  ply: { kind: 'material', material: 'ply', base: '#C9AE85', dark: '#8A7355', light: '#E2CDA8' },
  wpc: { kind: 'material', material: 'wpc', base: '#B8C4C0', dark: '#7E8F8A', light: '#DDE5E2' },
  doors: { kind: 'art', art: 'classic', tones: 'wood', defaultTone: 'teak' },
}

async function loadEnv() {
  try {
    const raw = await readFile(path.join(ROOT, '.env'), 'utf8')
    for (const line of raw.split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
      if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
    }
  } catch {
    // no .env — fine
  }
}

function emptyCatalog(reason) {
  return `/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * ${reason}
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = []
`
}

function toImage(img, alt) {
  if (!img?.src_480) return undefined
  return {
    src: img.src_480,
    srcSet: `${img.src_480} 480w, ${img.src_960 ?? img.src_480} 960w`,
    alt,
    w: img.width ?? 0,
    h: img.height ?? 0,
  }
}

function toVisual(row) {
  const images = (row.images ?? []).slice().sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0))
  const coverRow = images.find((i) => i.role === 'cover') ?? images[0]
  const cover = toImage(coverRow, row.name)
  if (cover) {
    const gallery = images
      .filter((i) => i !== coverRow)
      .map((i) => toImage(i, row.name))
      .filter(Boolean)
    return { kind: 'photo', cover, gallery, presentation: row.presentation ?? 'showcase' }
  }
  return MATERIAL[row.world] ?? MATERIAL.doors
}

await loadEnv()
const url = process.env.VITE_SUPABASE_URL
const key = process.env.VITE_SUPABASE_ANON_KEY

if (!url || !key) {
  await writeFile(OUT, emptyCatalog('No VITE_SUPABASE_URL configured — site uses local data only.'))
  console.log('catalog:fetch — no Supabase config; wrote empty catalog (local data only)')
  process.exit(0)
}

const select =
  'slug,name,world,tag,story,specs,purchasable,price,price_unit,presentation,sort_order,' +
  'subcategory:subcategories(name,slug,sort_order),' +
  'images:product_images(role,src_480,src_960,width,height,sort_order)'
const query = `${url}/rest/v1/products?select=${encodeURIComponent(select)}&published=eq.true&order=world.asc,sort_order.asc,name.asc`
const res = await fetch(query, { headers: { apikey: key, Authorization: `Bearer ${key}` } })
if (!res.ok) {
  console.error(`catalog:fetch failed: ${res.status} ${await res.text()}`)
  process.exit(1)
}
const rows = await res.json()

const products = rows
  .filter((r) => r.slug && r.name && r.world && r.subcategory?.name && r.tag)
  .map((r) => ({
    id: r.slug,
    name: r.name,
    world: r.world,
    sub: r.subcategory.name,
    tag: r.tag,
    ...(r.story ? { story: r.story } : {}),
    specs: r.specs ?? [],
    visual: toVisual(r),
    purchasable: Boolean(r.purchasable && r.price),
    ...(r.price ? { price: r.price } : {}),
    ...(r.price_unit ? { priceUnit: r.price_unit } : {}),
  }))

const ts = `/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * Fetched from Supabase at ${new Date().toISOString()} (${products.length} products).
 * CMS products override local ones by id (except Designer Studio) and new
 * slugs are appended — see the merge in products.ts.
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)}
`
await writeFile(OUT, ts)
console.log(`catalog:fetch — wrote ${products.length} products from Supabase`)
