/**
 * Pull the published catalogue from Supabase into the site bundle.
 *
 * Reads VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY from the environment or a
 * root `.env`, queries the public PostgREST API, converts rows to the site's
 * Product shape, and writes src/data/catalog.gen.ts. With no project
 * configured it writes an empty catalog and exits 0 — the site then runs on
 * the local data files alone.
 *
 * ⚠️ This is no longer the *only* path from /admin to the storefront. The site
 * also re-reads the same rows in the browser (src/data/liveCatalog.ts), so a
 * door the client adds appears without a deploy. What this still buys is the
 * first paint: the snapshot it writes is what renders before the live read
 * lands, and it is the whole catalogue when the network fails. Keep running it
 * in the build.
 *
 * ⚠️ The row → Product conversion lives in src/data/cmsMap.ts and is shared
 * with the browser rather than copied here. Two copies of "which rows count as
 * products" is exactly the kind of drift nobody notices until a door is
 * missing from one of them. Loaded through Vite's SSR loader, the way
 * build-sitemap.mjs already loads products.ts.
 *
 * Run: npm run catalog:fetch   (Vercel build: `npm run catalog:fetch && npm run build`)
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { createServer } from 'vite'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT = path.join(ROOT, 'src/data/catalog.gen.ts')

async function loadEnv() {
  try {
    const raw = await readFile(path.join(ROOT, '.env'), 'utf8')
    for (const line of raw.split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/)
      if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
    }
  } catch {
    // no .env — fine
  }
}

function emptyCatalog(reason) {
  return `/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * ${reason}
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = []
`
}

await loadEnv()
const url = process.env.VITE_SUPABASE_URL
const key = process.env.VITE_SUPABASE_ANON_KEY

if (!url || !key) {
  await writeFile(OUT, emptyCatalog('No VITE_SUPABASE_URL configured — site uses local data only.'))
  console.log('catalog:fetch — no Supabase config; wrote empty catalog (local data only)')
  process.exit(0)
}

const server = await createServer({ root: ROOT, logLevel: 'error', server: { middlewareMode: true } })
let mapCatalogue, CMS_SELECT, CMS_ORDER
try {
  ;({ mapCatalogue, CMS_SELECT, CMS_ORDER } = await server.ssrLoadModule('/src/data/cmsMap.ts'))
} finally {
  await server.close()
}

const query = `${url}/rest/v1/products?select=${encodeURIComponent(CMS_SELECT)}&published=eq.true&order=${CMS_ORDER}`
const res = await fetch(query, { headers: { apikey: key, Authorization: `Bearer ${key}` } })
if (!res.ok) {
  console.error(`catalog:fetch failed: ${res.status} ${await res.text()}`)
  process.exit(1)
}
const rows = await res.json()
const { products } = mapCatalogue(rows)

const ts = `/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * Fetched from Supabase at ${new Date().toISOString()} (${products.length} products).
 * CMS products override local ones by id and new slugs are appended — see the
 * merge in products.ts. The storefront re-reads the same rows live in the
 * browser (liveCatalog.ts); this is the copy it paints with first.
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)}
`
await writeFile(OUT, ts)
console.log(`catalog:fetch — wrote ${products.length} products from Supabase`)
