/**
 * Door photo pipeline.
 *
 * Reads the raw photo folders ("Main Doors", "Room Doors" — gitignored, never
 * shipped), auto-rotates, resizes to 480/960 widths, encodes webp, and writes
 * slug-named files to public/images/doors/ plus a typed manifest at
 * src/data/images.gen.ts.
 *
 * Deterministic: source files are processed in sorted filename order, so slugs
 * (main-01, main-02, … room-01, …) are stable as long as no files are
 * added/removed before existing ones. Re-run with `npm run images:build`.
 */
import { createHash } from 'node:crypto'
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const ROOT = path.resolve(import.meta.dirname, '..')
const SOURCES = [
  { dir: path.join(ROOT, 'Main Doors'), prefix: 'main' },
  { dir: path.join(ROOT, 'Room Doors'), prefix: 'room' },
]
const OUT_DIR = path.join(ROOT, 'public/images/doors')
const MANIFEST = path.join(ROOT, 'src/data/images.gen.ts')
const WIDTHS = [480, 960]
const QUALITY = 72
const EXT = /\.(jpe?g|png|webp)$/i

await rm(OUT_DIR, { recursive: true, force: true })
await mkdir(OUT_DIR, { recursive: true })

const entries = []
let inBytes = 0
let outBytes = 0

for (const { dir, prefix } of SOURCES) {
  let files
  try {
    files = (await readdir(dir)).filter((f) => EXT.test(f)).sort()
  } catch {
    console.warn(`skip: ${dir} not found`)
    continue
  }
  let n = 0
  for (const file of files) {
    n += 1
    const id = `${prefix}-${String(n).padStart(2, '0')}`
    const buf = await readFile(path.join(dir, file))
    inBytes += buf.length
    const img = sharp(buf).rotate() // respect EXIF orientation
    const meta = await img.metadata()
    const outs = []
    for (const w of WIDTHS) {
      const width = Math.min(w, meta.width ?? w)
      const out = await img.clone().resize({ width }).webp({ quality: QUALITY }).toBuffer()
      const outName = `${id}-${w}.webp`
      await writeFile(path.join(OUT_DIR, outName), out)
      outBytes += out.length
      outs.push({ w, name: outName })
    }
    const full = await sharp(buf).rotate().metadata()
    entries.push({
      id,
      src: `/images/doors/${id}-480.webp`,
      srcSet: outs.map((o) => `/images/doors/${o.name} ${o.w}w`).join(', '),
      w: full.width ?? 0,
      h: full.height ?? 0,
      sourceHash: createHash('md5').update(buf).digest('hex').slice(0, 8),
      sourceFile: file,
    })
  }
  console.log(`${prefix}: ${n} images`)
}

const ts = `/**
 * GENERATED by scripts/import-images.mjs — do not edit by hand.
 * Maps image ids (main-NN / room-NN) to processed webp files.
 * Curation: data/photoMap.ts decides which product uses which image.
 */
import type { ProductImage } from './products'

export interface DoorImage extends Omit<ProductImage, 'alt'> {
  /** original filename in the raw folder, for re-curation */
  sourceFile: string
}

export const DOOR_IMAGES: Record<string, DoorImage> = {
${entries
  .map(
    (e) =>
      `  '${e.id}': { src: '${e.src}', srcSet: '${e.srcSet}', w: ${e.w}, h: ${e.h}, sourceFile: '${e.sourceFile}' },`,
  )
  .join('\n')}
}
`
await writeFile(MANIFEST, ts)

console.log(
  `done: ${entries.length} images → ${OUT_DIR}\n` +
    `input ${(inBytes / 1e6).toFixed(1)} MB → output ${(outBytes / 1e6).toFixed(1)} MB`,
)
