import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
/* Self-hosted brand faces. Must come before global.css so the @font-face rules
   are registered by the time --serif/--sans are used. Generated by
   scripts/fetch-fonts.mjs; the latin subsets are preloaded from index.html. */
import './styles/fonts.css'
import './styles/global.css'
import './styles/worlds.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
