/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * Fetched from Supabase at 2026-08-17T12:20:00.114Z (37 products).
 * CMS products override local ones by id (except Designer Studio) and new
 * slugs are appended — see the merge in products.ts.
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = [
  {
    "id": "burma-teak-door",
    "name": "Burma Teak Door",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Solid Burma teak, panel by panel — the heirloom door",
    "specs": [
      "Solid Burma teak throughout",
      "Traditional panel construction",
      "Ready for polish of your choice",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-04-480.webp",
        "srcSet": "/images/doors/main-04-480.webp 480w, /images/doors/main-04-960.webp 960w",
        "alt": "Burma Teak Door",
        "w": 1080,
        "h": 1920
      },
      "gallery": [
        {
          "src": "/images/doors/main-40-480.webp",
          "srcSet": "/images/doors/main-40-480.webp 480w, /images/doors/main-40-960.webp 960w",
          "alt": "Burma Teak Door",
          "w": 1080,
          "h": 1920
        },
        {
          "src": "/images/doors/main-42-480.webp",
          "srcSet": "/images/doors/main-42-480.webp 480w, /images/doors/main-42-960.webp 960w",
          "alt": "Burma Teak Door",
          "w": 942,
          "h": 1674
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "burma-border-teak-door",
    "name": "Burma Border Teak Door",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Border teak build with the classic teak face",
    "specs": [
      "Burma-border teak sections",
      "Solid panel or glazed layouts",
      "Seasoned to resist warping",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-25-480.webp",
        "srcSet": "/images/doors/main-25-480.webp 480w, /images/doors/main-25-960.webp 960w",
        "alt": "Burma Border Teak Door",
        "w": 867,
        "h": 1156
      },
      "gallery": [
        {
          "src": "/images/doors/main-10-480.webp",
          "srcSet": "/images/doors/main-10-480.webp 480w, /images/doors/main-10-960.webp 960w",
          "alt": "Burma Border Teak Door",
          "w": 926,
          "h": 1540
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "teak-osc-2nds",
    "name": "2nds Teak OSC Doors",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "One-side-clear teak seconds — real teak, real value",
    "specs": [
      "One side clear (OSC) teak grade",
      "Minor natural marks on reverse face",
      "The economical way into solid teak",
      "Limited stock, per-piece pricing"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-41-480.webp",
        "srcSet": "/images/doors/main-41-480.webp 480w, /images/doors/main-41-960.webp 960w",
        "alt": "2nds Teak OSC Doors",
        "w": 1080,
        "h": 1920
      },
      "gallery": [
        {
          "src": "/images/doors/main-05-480.webp",
          "srcSet": "/images/doors/main-05-480.webp 480w, /images/doors/main-05-960.webp 960w",
          "alt": "2nds Teak OSC Doors",
          "w": 1080,
          "h": 1920
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "gana-teak-polish-door",
    "name": "Gana Teak Polish Doors",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Ghana teak, delivered pre-polished and ready to hang",
    "specs": [
      "Ghana teak, factory polish finish",
      "No on-site polishing needed",
      "Consistent sheen across the leaf",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-09-480.webp",
        "srcSet": "/images/doors/main-09-480.webp 480w, /images/doors/main-09-960.webp 960w",
        "alt": "Gana Teak Polish Doors",
        "w": 643,
        "h": 1080
      },
      "gallery": [
        {
          "src": "/images/doors/main-02-480.webp",
          "srcSet": "/images/doors/main-02-480.webp 480w, /images/doors/main-02-960.webp 960w",
          "alt": "Gana Teak Polish Doors",
          "w": 1024,
          "h": 1024
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "architect-teak-door",
    "name": "Architect Teak Doors",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Architect-spec teak doors built to drawing",
    "specs": [
      "Built to architect drawings & sections",
      "Custom panels, glazing & grooves",
      "Site-matched polish samples",
      "Project & bulk friendly"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-34-480.webp",
        "srcSet": "/images/doors/main-34-480.webp 480w, /images/doors/main-34-960.webp 960w",
        "alt": "Architect Teak Doors",
        "w": 768,
        "h": 1361
      },
      "gallery": [
        {
          "src": "/images/doors/main-36-480.webp",
          "srcSet": "/images/doors/main-36-480.webp 480w, /images/doors/main-36-960.webp 960w",
          "alt": "Architect Teak Doors",
          "w": 693,
          "h": 1280
        },
        {
          "src": "/images/doors/main-48-480.webp",
          "srcSet": "/images/doors/main-48-480.webp 480w, /images/doors/main-48-960.webp 960w",
          "alt": "Architect Teak Doors",
          "w": 1024,
          "h": 1024
        },
        {
          "src": "/images/doors/main-49-480.webp",
          "srcSet": "/images/doors/main-49-480.webp 480w, /images/doors/main-49-960.webp 960w",
          "alt": "Architect Teak Doors",
          "w": 1080,
          "h": 1920
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "honne-ab-door",
    "name": "Honne A & B Grade Doors",
    "world": "doors",
    "sub": "Hardwood Doors",
    "tag": "Dense honne hardwood doors in A and B grades",
    "specs": [
      "Australian/Malaysian honne builds",
      "A & B grades to suit budget",
      "Heavy, solid, secure feel",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-27-480.webp",
        "srcSet": "/images/doors/main-27-480.webp 480w, /images/doors/main-27-960.webp 960w",
        "alt": "Honne A & B Grade Doors",
        "w": 1004,
        "h": 1600
      },
      "gallery": [
        {
          "src": "/images/doors/main-33-480.webp",
          "srcSet": "/images/doors/main-33-480.webp 480w, /images/doors/main-33-960.webp 960w",
          "alt": "Honne A & B Grade Doors",
          "w": 1080,
          "h": 1920
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "mahagony-ab-door",
    "name": "Mahagony A & B Grade Doors",
    "world": "doors",
    "sub": "Hardwood Doors",
    "tag": "Rich mahogany doors, two grades, one look",
    "specs": [
      "Plantation mahogany construction",
      "A & B grades available",
      "Takes deep polish beautifully",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-16-480.webp",
        "srcSet": "/images/doors/main-16-480.webp 480w, /images/doors/main-16-960.webp 960w",
        "alt": "Mahagony A & B Grade Doors",
        "w": 472,
        "h": 788
      },
      "gallery": [
        {
          "src": "/images/doors/main-22-480.webp",
          "srcSet": "/images/doors/main-22-480.webp 480w, /images/doors/main-22-960.webp 960w",
          "alt": "Mahagony A & B Grade Doors",
          "w": 720,
          "h": 960
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "veneer-designer-door",
    "name": "Veneer Designer Doors",
    "world": "doors",
    "sub": "Veneer Doors",
    "tag": "Natural veneer faces in designer layouts",
    "specs": [
      "Natural wood veneer skins",
      "Designer groove & inlay patterns",
      "Solid engineered core",
      "Polish or PU finish options"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-03-480.webp",
        "srcSet": "/images/doors/room-03-480.webp 480w, /images/doors/room-03-960.webp 960w",
        "alt": "Veneer Designer Doors",
        "w": 1800,
        "h": 2500
      },
      "gallery": [
        {
          "src": "/images/doors/main-13-480.webp",
          "srcSet": "/images/doors/main-13-480.webp 480w, /images/doors/main-13-960.webp 960w",
          "alt": "Veneer Designer Doors",
          "w": 1024,
          "h": 1536
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "veneer-cng-door",
    "name": "Veneer CNG Doors",
    "world": "doors",
    "sub": "Veneer Doors",
    "tag": "CNC-carved grooves through natural veneer",
    "specs": [
      "CNC-routed face patterns",
      "Natural veneer over solid core",
      "Crisp, repeatable detailing",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-11-480.webp",
        "srcSet": "/images/doors/main-11-480.webp 480w, /images/doors/main-11-960.webp 960w",
        "alt": "Veneer CNG Doors",
        "w": 800,
        "h": 1200
      },
      "gallery": [
        {
          "src": "/images/doors/main-20-480.webp",
          "srcSet": "/images/doors/main-20-480.webp 480w, /images/doors/main-20-960.webp 960w",
          "alt": "Veneer CNG Doors",
          "w": 640,
          "h": 640
        },
        {
          "src": "/images/doors/main-38-480.webp",
          "srcSet": "/images/doors/main-38-480.webp 480w, /images/doors/main-38-960.webp 960w",
          "alt": "Veneer CNG Doors",
          "w": 271,
          "h": 500
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "laminate-cng-door",
    "name": "Laminate CNG Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "CNC pattern work on tough laminate faces",
    "specs": [
      "CNC-routed laminate face",
      "Scratch & stain resistant",
      "Solid engineered core",
      "Wide shade card available"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-31-480.webp",
        "srcSet": "/images/doors/room-31-480.webp 480w, /images/doors/room-31-960.webp 960w",
        "alt": "Laminate CNG Doors",
        "w": 480,
        "h": 420
      },
      "gallery": [
        {
          "src": "/images/doors/room-45-480.webp",
          "srcSet": "/images/doors/room-45-480.webp 480w, /images/doors/room-45-960.webp 960w",
          "alt": "Laminate CNG Doors",
          "w": 1000,
          "h": 1000
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "laminate-designer-door",
    "name": "Laminate Designer Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "Designer laminates — grain, colour and texture",
    "specs": [
      "1 mm high-pressure laminate",
      "Wood, solid & textured shades",
      "Moisture-guard edge banding",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-20-480.webp",
        "srcSet": "/images/doors/room-20-480.webp 480w, /images/doors/room-20-960.webp 960w",
        "alt": "Laminate Designer Doors",
        "w": 1800,
        "h": 2500
      },
      "gallery": [
        {
          "src": "/images/doors/room-07-480.webp",
          "srcSet": "/images/doors/room-07-480.webp 480w, /images/doors/room-07-960.webp 960w",
          "alt": "Laminate Designer Doors",
          "w": 760,
          "h": 950
        },
        {
          "src": "/images/doors/room-35-480.webp",
          "srcSet": "/images/doors/room-35-480.webp 480w, /images/doors/room-35-960.webp 960w",
          "alt": "Laminate Designer Doors",
          "w": 808,
          "h": 1610
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "microcoat-door",
    "name": "Lamination / MicroCoated Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "Micro-coated skins — smooth, sealed, economical",
    "specs": [
      "Micro-lamination coated face",
      "Uniform finish, easy to clean",
      "Economical for full projects",
      "Multiple shades available"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-44-480.webp",
        "srcSet": "/images/doors/room-44-480.webp 480w, /images/doors/room-44-960.webp 960w",
        "alt": "Lamination / MicroCoated Doors",
        "w": 640,
        "h": 1030
      },
      "gallery": [
        {
          "src": "/images/doors/room-24-480.webp",
          "srcSet": "/images/doors/room-24-480.webp 480w, /images/doors/room-24-960.webp 960w",
          "alt": "Lamination / MicroCoated Doors",
          "w": 2667,
          "h": 4292
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "primer-door",
    "name": "Primer Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "Primer-finished flush doors, ready for your paint",
    "specs": [
      "Factory primer coat, paint-ready",
      "Smooth sanded flush face",
      "Pick any site-painted colour",
      "Project & bulk friendly"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-10-480.webp",
        "srcSet": "/images/doors/room-10-480.webp 480w, /images/doors/room-10-960.webp 960w",
        "alt": "Primer Doors",
        "w": 736,
        "h": 1104
      },
      "gallery": [
        {
          "src": "/images/doors/room-22-480.webp",
          "srcSet": "/images/doors/room-22-480.webp 480w, /images/doors/room-22-960.webp 960w",
          "alt": "Primer Doors",
          "w": 1080,
          "h": 1350
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "korean-membrane-door",
    "name": "Korean Membrane Doors",
    "world": "doors",
    "sub": "Membrane Doors",
    "tag": "Imported Korean membrane — deeper texture, tighter wrap",
    "specs": [
      "Imported Korean membrane foil",
      "Seamless wrap over routed face",
      "Rich texture & matte options",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-30-480.webp",
        "srcSet": "/images/doors/room-30-480.webp 480w, /images/doors/room-30-960.webp 960w",
        "alt": "Korean Membrane Doors",
        "w": 736,
        "h": 1397
      },
      "gallery": [
        {
          "src": "/images/doors/room-39-480.webp",
          "srcSet": "/images/doors/room-39-480.webp 480w, /images/doors/room-39-960.webp 960w",
          "alt": "Korean Membrane Doors",
          "w": 720,
          "h": 900
        },
        {
          "src": "/images/doors/room-28-480.webp",
          "srcSet": "/images/doors/room-28-480.webp 480w, /images/doors/room-28-960.webp 960w",
          "alt": "Korean Membrane Doors",
          "w": 2147,
          "h": 4000
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "membrane-door",
    "name": "Membrane Doors",
    "world": "doors",
    "sub": "Membrane Doors",
    "tag": "Seamless membrane-wrapped designs in many shades",
    "specs": [
      "Membrane foil over MDF face",
      "Seamless, groove-friendly wrap",
      "Wide design & shade range",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-33-480.webp",
        "srcSet": "/images/doors/room-33-480.webp 480w, /images/doors/room-33-960.webp 960w",
        "alt": "Membrane Doors",
        "w": 1000,
        "h": 1000
      },
      "gallery": [
        {
          "src": "/images/doors/room-50-480.webp",
          "srcSet": "/images/doors/room-50-480.webp 480w, /images/doors/room-50-960.webp 960w",
          "alt": "Membrane Doors",
          "w": 543,
          "h": 815
        },
        {
          "src": "/images/doors/room-38-480.webp",
          "srcSet": "/images/doors/room-38-480.webp 480w, /images/doors/room-38-960.webp 960w",
          "alt": "Membrane Doors",
          "w": 750,
          "h": 750
        },
        {
          "src": "/images/doors/room-05-480.webp",
          "srcSet": "/images/doors/room-05-480.webp 480w, /images/doors/room-05-960.webp 960w",
          "alt": "Membrane Doors",
          "w": 2642,
          "h": 5373
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "xtreme-ply",
    "name": "XTREME Ply & B/B",
    "world": "ply",
    "sub": "Plywood",
    "tag": "Flagship ply and blockboard for hard-working interiors",
    "specs": [
      "Plywood + blockboard range",
      "Dense, gap-free core",
      "Uniform thickness, low warp",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xplor-ply",
    "name": "XPLOR Ply",
    "world": "ply",
    "sub": "Plywood",
    "tag": "Dependable commercial ply for everyday furniture",
    "specs": [
      "Commercial MR grade",
      "Smooth calibrated faces",
      "Furniture & panelling",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xlent-ply",
    "name": "XLENT Ply",
    "world": "ply",
    "sub": "Plywood",
    "tag": "Step-up ply with tighter cores and cleaner faces",
    "specs": [
      "Premium MR grade",
      "Screw-holding certified",
      "Kitchens & wardrobes",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xlent-710-ply",
    "name": "XLENT 710 Ply",
    "world": "ply",
    "sub": "710 Marine Grade",
    "tag": "Boiling-waterproof 710 for kitchens and bathrooms",
    "specs": [
      "IS:710 BWP marine grade",
      "72-hour boil tested",
      "Kitchens, baths, exteriors",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtron-calibrated",
    "name": "XTRON Calibrated Ply",
    "world": "ply",
    "sub": "Calibrated",
    "tag": "Machine-calibrated thickness for flawless laminates",
    "specs": [
      "European calibration line",
      "±0.2 mm thickness tolerance",
      "Zero undulation under laminate",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtron-club-prime-710",
    "name": "XTRON CLUB PRIME 710",
    "world": "ply",
    "sub": "710 Marine Grade",
    "tag": "Club-grade 710 with hardwood throughout",
    "specs": [
      "IS:710 BWP, full hardwood core",
      "Chemically treated, borer-proof",
      "Heavy-duty furniture & marine use",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtron-signature-710",
    "name": "XTRON SIGNATURE 710",
    "world": "ply",
    "sub": "710 Marine Grade",
    "tag": "The signature sheet — our best core, our best face",
    "specs": [
      "Flagship IS:710 BWP grade",
      "A+ faces both sides",
      "Lifetime warranty programme",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtorq-bb",
    "name": "XTORQ B/B Pine & H/W",
    "world": "ply",
    "sub": "Blockboard",
    "tag": "Pine and hardwood blockboards that stay dead straight",
    "specs": [
      "Seasoned pine / hardwood battens",
      "No sag on long spans",
      "Wardrobe shutters & panels",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "burmese-teak",
    "name": "Burmese Teak",
    "world": "timbers",
    "sub": "Teak",
    "tag": "The benchmark — tight grain, natural oils, decades of life",
    "specs": [
      "Imported Burma teak logs, sawn in-house",
      "High natural oil content — termite & rot resistant",
      "Ideal for main doors, frames & carving",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "burma-border-teak",
    "name": "Burma Border Teak",
    "world": "timbers",
    "sub": "Teak",
    "tag": "Border-grade Burma teak — the classic look, keener price",
    "specs": [
      "Burma-border teak, graded and seasoned",
      "Straight grain, warm golden tone",
      "Doors, frames, windows & furniture",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "gana-teak",
    "name": "Gana Teak Wood",
    "world": "timbers",
    "sub": "Teak",
    "tag": "African teak with bold figure — strong and stable",
    "specs": [
      "Ghana teak, kiln-seasoned",
      "Pronounced grain figure",
      "Good stability across seasons",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "commercial-teak",
    "name": "Commercial Teak Wood",
    "world": "timbers",
    "sub": "Teak",
    "tag": "Everyday teak for frames and general woodwork",
    "specs": [
      "Budget-friendly teak grade",
      "Frames, shutters & general carpentry",
      "Machined to your sizes",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "australian-honne",
    "name": "Australian Honne Wood",
    "world": "timbers",
    "sub": "Honne",
    "tag": "Dense reddish hardwood — takes polish beautifully",
    "specs": [
      "Imported Australian honne",
      "High density, excellent screw-holding",
      "Doors, frames & heavy sections",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "malaysian-honne",
    "name": "Malaysian Honne Wood",
    "world": "timbers",
    "sub": "Honne",
    "tag": "Workhorse hardwood for frames and structure",
    "specs": [
      "Malaysian honne (kapur family)",
      "Uniform texture, easy to machine",
      "Frames, beams & windows",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "redsal",
    "name": "Redsal Wood",
    "world": "timbers",
    "sub": "Sal",
    "tag": "Load-bearing red sal — the builder’s hardwood",
    "specs": [
      "Seasoned red sal",
      "Very high strength & durability",
      "Structural work, frames, rafters",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "whitesal",
    "name": "Whitesal Wood",
    "world": "timbers",
    "sub": "Sal",
    "tag": "Light-toned sal for frames and utility work",
    "specs": [
      "Seasoned white sal",
      "Straight sections, economical",
      "Frames & general construction",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "mahagony",
    "name": "Mahagony Wood",
    "world": "timbers",
    "sub": "Hardwood & Neem",
    "tag": "Deep reddish-brown, fine grain — furniture royalty",
    "specs": [
      "Plantation mahogany, kiln-dried",
      "Fine, even grain — carves & polishes well",
      "Furniture, panelling, doors",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "neem-premium",
    "name": "Neem Premium",
    "world": "timbers",
    "sub": "Hardwood & Neem",
    "tag": "Naturally pest-resistant, select grade",
    "specs": [
      "Select-grade seasoned neem",
      "Naturally insect-repellent timber",
      "Doors, frames & shelving",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "neem-regular",
    "name": "Neem Regular",
    "world": "timbers",
    "sub": "Hardwood & Neem",
    "tag": "Honest, economical hardwood for everyday work",
    "specs": [
      "Standard-grade seasoned neem",
      "Economical all-rounder",
      "Utility doors & frames",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "wpc-sheets",
    "name": "WPC Solid Sheets",
    "world": "wpc",
    "sub": "WPC Sheets",
    "tag": "100% waterproof boards — 6 mm to 18 mm, two densities",
    "specs": [
      "Thicknesses: 18 / 16 / 12 / 8 / 6 mm",
      "Densities: 0.45 & 0.55",
      "Waterproof, termite-proof, fire-retardant",
      "Screws, routs & paints like wood"
    ],
    "visual": {
      "kind": "material",
      "material": "wpc",
      "base": "#B8C4C0",
      "dark": "#7E8F8A",
      "light": "#DDE5E2"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "wpc-cnc-door",
    "name": "28 mm CNC WPC Doors",
    "world": "wpc",
    "sub": "WPC Doors",
    "tag": "CNC-carved WPC doors — zero swelling, ever",
    "specs": [
      "28 mm solid WPC leaf",
      "CNC-carved face designs",
      "Bathroom & utility safe — 100% waterproof",
      "Paint or PU finish options"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/room-25-480.webp",
        "srcSet": "/images/doors/room-25-480.webp 480w, /images/doors/room-25-960.webp 960w",
        "alt": "28 mm CNC WPC Doors",
        "w": 645,
        "h": 1201
      },
      "gallery": [
        {
          "src": "/images/doors/room-23-480.webp",
          "srcSet": "/images/doors/room-23-480.webp 480w, /images/doors/room-23-960.webp 960w",
          "alt": "28 mm CNC WPC Doors",
          "w": 3808,
          "h": 5704
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "wpc-digital-veneer-door",
    "name": "Digital Veneer WPC Doors",
    "world": "wpc",
    "sub": "WPC Doors",
    "tag": "28 & 30 mm WPC with photo-real digital veneer faces",
    "specs": [
      "28 mm & 30 mm leaves",
      "Digital-printed veneer textures",
      "Waterproof core, UV-stable print",
      "Wood looks without wood worries"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "/images/doors/main-03-480.webp",
        "srcSet": "/images/doors/main-03-480.webp 480w, /images/doors/main-03-960.webp 960w",
        "alt": "Digital Veneer WPC Doors",
        "w": 1024,
        "h": 1536
      },
      "gallery": [
        {
          "src": "/images/doors/main-39-480.webp",
          "srcSet": "/images/doors/main-39-480.webp 480w, /images/doors/main-39-960.webp 960w",
          "alt": "Digital Veneer WPC Doors",
          "w": 1650,
          "h": 2775
        }
      ],
      "presentation": "swing"
    },
    "purchasable": false,
    "priceUnit": "leaf"
  }
]
