/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * Fetched from Sanity project sn4590lo/production at 2026-07-20T05:58:52.787Z.
 * CMS products override local ones by id (except Designer Studio) and new
 * slugs are appended — see the merge in products.ts.
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = [
  {
    "id": "honne-ab-door",
    "name": "Honne A & B Grade Doors",
    "world": "doors",
    "sub": "Hardwood Doors",
    "tag": "Dense honne hardwood doors in A and B grades",
    "specs": [
      "Australian/Malaysian honne builds",
      "A & B grades to suit budget",
      "Heavy, solid, secure feel",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/dda2f82ad4f2362c67d636cc9afad0beaf17006d-960x1530.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/dda2f82ad4f2362c67d636cc9afad0beaf17006d-960x1530.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/dda2f82ad4f2362c67d636cc9afad0beaf17006d-960x1530.webp?w=960&fm=webp&q=75 960w",
        "alt": "Honne A & B Grade Doors",
        "w": 960,
        "h": 1530
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/ba7590def558cd8981e1c902222e96162d16ebaa-960x1707.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/ba7590def558cd8981e1c902222e96162d16ebaa-960x1707.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/ba7590def558cd8981e1c902222e96162d16ebaa-960x1707.webp?w=960&fm=webp&q=75 960w",
          "alt": "Honne A & B Grade Doors",
          "w": 960,
          "h": 1707
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "mahagony-ab-door",
    "name": "Mahagony A & B Grade Doors",
    "world": "doors",
    "sub": "Hardwood Doors",
    "tag": "Rich mahogany doors, two grades, one look",
    "specs": [
      "Plantation mahogany construction",
      "A & B grades available",
      "Takes deep polish beautifully",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/818591d02ccc550bce2eed2ae346f4392eb413c8-472x788.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/818591d02ccc550bce2eed2ae346f4392eb413c8-472x788.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/818591d02ccc550bce2eed2ae346f4392eb413c8-472x788.webp?w=960&fm=webp&q=75 960w",
        "alt": "Mahagony A & B Grade Doors",
        "w": 472,
        "h": 788
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/de9a4d1025abf138a873d8150c0848367f6bd8dc-720x960.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/de9a4d1025abf138a873d8150c0848367f6bd8dc-720x960.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/de9a4d1025abf138a873d8150c0848367f6bd8dc-720x960.webp?w=960&fm=webp&q=75 960w",
          "alt": "Mahagony A & B Grade Doors",
          "w": 720,
          "h": 960
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "laminate-cng-door",
    "name": "Laminate CNG Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "CNC pattern work on tough laminate faces",
    "specs": [
      "CNC-routed laminate face",
      "Scratch & stain resistant",
      "Solid engineered core",
      "Wide shade card available"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/808c531d0be136f9ed79f727c7c7f97cb319761d-480x420.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/808c531d0be136f9ed79f727c7c7f97cb319761d-480x420.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/808c531d0be136f9ed79f727c7c7f97cb319761d-480x420.webp?w=960&fm=webp&q=75 960w",
        "alt": "Laminate CNG Doors",
        "w": 480,
        "h": 420
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/fac14d607a411ed51bf4423f8d37f6f1917b7f33-960x960.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/fac14d607a411ed51bf4423f8d37f6f1917b7f33-960x960.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/fac14d607a411ed51bf4423f8d37f6f1917b7f33-960x960.webp?w=960&fm=webp&q=75 960w",
          "alt": "Laminate CNG Doors",
          "w": 960,
          "h": 960
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "laminate-designer-door",
    "name": "Laminate Designer Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "Designer laminates — grain, colour and texture",
    "specs": [
      "1 mm high-pressure laminate",
      "Wood, solid & textured shades",
      "Moisture-guard edge banding",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/602a82fd1455ca88986c76134f478d0232b41846-960x1333.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/602a82fd1455ca88986c76134f478d0232b41846-960x1333.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/602a82fd1455ca88986c76134f478d0232b41846-960x1333.webp?w=960&fm=webp&q=75 960w",
        "alt": "Laminate Designer Doors",
        "w": 960,
        "h": 1333
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/90041622f3871c2ec01ad94e02dec5c23126ebc3-760x950.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/90041622f3871c2ec01ad94e02dec5c23126ebc3-760x950.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/90041622f3871c2ec01ad94e02dec5c23126ebc3-760x950.webp?w=960&fm=webp&q=75 960w",
          "alt": "Laminate Designer Doors",
          "w": 760,
          "h": 950
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/fe5688fffe9c0704835551fd71e5cc66e18535e6-808x1610.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/fe5688fffe9c0704835551fd71e5cc66e18535e6-808x1610.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/fe5688fffe9c0704835551fd71e5cc66e18535e6-808x1610.webp?w=960&fm=webp&q=75 960w",
          "alt": "Laminate Designer Doors",
          "w": 808,
          "h": 1610
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "microcoat-door",
    "name": "Lamination / MicroCoated Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "Micro-coated skins — smooth, sealed, economical",
    "specs": [
      "Micro-lamination coated face",
      "Uniform finish, easy to clean",
      "Economical for full projects",
      "Multiple shades available"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/b9da4f2a2377c884d541e1eff64d5a96dd32fc5e-640x1030.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/b9da4f2a2377c884d541e1eff64d5a96dd32fc5e-640x1030.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/b9da4f2a2377c884d541e1eff64d5a96dd32fc5e-640x1030.webp?w=960&fm=webp&q=75 960w",
        "alt": "Lamination / MicroCoated Doors",
        "w": 640,
        "h": 1030
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/20b45ae43464584d06fe1e5b536229d4de5d921f-960x1545.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/20b45ae43464584d06fe1e5b536229d4de5d921f-960x1545.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/20b45ae43464584d06fe1e5b536229d4de5d921f-960x1545.webp?w=960&fm=webp&q=75 960w",
          "alt": "Lamination / MicroCoated Doors",
          "w": 960,
          "h": 1545
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "primer-door",
    "name": "Primer Doors",
    "world": "doors",
    "sub": "Laminate & Coated",
    "tag": "Primer-finished flush doors, ready for your paint",
    "specs": [
      "Factory primer coat, paint-ready",
      "Smooth sanded flush face",
      "Pick any site-painted colour",
      "Project & bulk friendly"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/0b853f0752de5f1f3cafe6a71e9ed6e38b24dbc5-736x1104.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/0b853f0752de5f1f3cafe6a71e9ed6e38b24dbc5-736x1104.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/0b853f0752de5f1f3cafe6a71e9ed6e38b24dbc5-736x1104.webp?w=960&fm=webp&q=75 960w",
        "alt": "Primer Doors",
        "w": 736,
        "h": 1104
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/6ba9c08af15972d34d2520433adf3258742dcc58-960x1200.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/6ba9c08af15972d34d2520433adf3258742dcc58-960x1200.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/6ba9c08af15972d34d2520433adf3258742dcc58-960x1200.webp?w=960&fm=webp&q=75 960w",
          "alt": "Primer Doors",
          "w": 960,
          "h": 1200
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "korean-membrane-door",
    "name": "Korean Membrane Doors",
    "world": "doors",
    "sub": "Membrane Doors",
    "tag": "Imported Korean membrane — deeper texture, tighter wrap",
    "specs": [
      "Imported Korean membrane foil",
      "Seamless wrap over routed face",
      "Rich texture & matte options",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/a8ae7b5724bfc5099f63ee0fd4b71c44af6d9986-736x1397.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/a8ae7b5724bfc5099f63ee0fd4b71c44af6d9986-736x1397.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/a8ae7b5724bfc5099f63ee0fd4b71c44af6d9986-736x1397.webp?w=960&fm=webp&q=75 960w",
        "alt": "Korean Membrane Doors",
        "w": 736,
        "h": 1397
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/ed2705bb27276978720b43893f78c291fcfe1dd0-720x900.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/ed2705bb27276978720b43893f78c291fcfe1dd0-720x900.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/ed2705bb27276978720b43893f78c291fcfe1dd0-720x900.webp?w=960&fm=webp&q=75 960w",
          "alt": "Korean Membrane Doors",
          "w": 720,
          "h": 900
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/fcfcdda95b7ee00bd71275f42e13a50ab5901e43-960x1789.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/fcfcdda95b7ee00bd71275f42e13a50ab5901e43-960x1789.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/fcfcdda95b7ee00bd71275f42e13a50ab5901e43-960x1789.webp?w=960&fm=webp&q=75 960w",
          "alt": "Korean Membrane Doors",
          "w": 960,
          "h": 1789
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "membrane-door",
    "name": "Membrane Doors",
    "world": "doors",
    "sub": "Membrane Doors",
    "tag": "Seamless membrane-wrapped designs in many shades",
    "specs": [
      "Membrane foil over MDF face",
      "Seamless, groove-friendly wrap",
      "Wide design & shade range",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/e17af16dea6419057cb5ec2b294973100b001dc6-960x960.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/e17af16dea6419057cb5ec2b294973100b001dc6-960x960.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/e17af16dea6419057cb5ec2b294973100b001dc6-960x960.webp?w=960&fm=webp&q=75 960w",
        "alt": "Membrane Doors",
        "w": 960,
        "h": 960
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/41e4028c6e200a616ffced2d79a4c66310f9d7de-543x815.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/41e4028c6e200a616ffced2d79a4c66310f9d7de-543x815.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/41e4028c6e200a616ffced2d79a4c66310f9d7de-543x815.webp?w=960&fm=webp&q=75 960w",
          "alt": "Membrane Doors",
          "w": 543,
          "h": 815
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/4b5aa46a35023fa907fea8ad279a0cd454b1dcc9-750x750.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/4b5aa46a35023fa907fea8ad279a0cd454b1dcc9-750x750.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/4b5aa46a35023fa907fea8ad279a0cd454b1dcc9-750x750.webp?w=960&fm=webp&q=75 960w",
          "alt": "Membrane Doors",
          "w": 750,
          "h": 750
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/f9742c73028eec590457f82ced12d1c8a0af8546-960x1952.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/f9742c73028eec590457f82ced12d1c8a0af8546-960x1952.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/f9742c73028eec590457f82ced12d1c8a0af8546-960x1952.webp?w=960&fm=webp&q=75 960w",
          "alt": "Membrane Doors",
          "w": 960,
          "h": 1952
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "burma-teak-door",
    "name": "Burma Teak Door",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Solid Burma teak, panel by panel — the heirloom door",
    "specs": [
      "Solid Burma teak throughout",
      "Traditional panel construction",
      "Ready for polish of your choice",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/a8320baf26ff3a08a437823d2f8fa8e6e9d5ff8b-960x1707.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/a8320baf26ff3a08a437823d2f8fa8e6e9d5ff8b-960x1707.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/a8320baf26ff3a08a437823d2f8fa8e6e9d5ff8b-960x1707.webp?w=960&fm=webp&q=75 960w",
        "alt": "Burma Teak Door",
        "w": 960,
        "h": 1707
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/15436748746db5cf140f3c6cf7443b9b73f716cc-960x1707.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/15436748746db5cf140f3c6cf7443b9b73f716cc-960x1707.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/15436748746db5cf140f3c6cf7443b9b73f716cc-960x1707.webp?w=960&fm=webp&q=75 960w",
          "alt": "Burma Teak Door",
          "w": 960,
          "h": 1707
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/1c328e0ada038e1a2999a6e6877f09646d981755-942x1674.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/1c328e0ada038e1a2999a6e6877f09646d981755-942x1674.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/1c328e0ada038e1a2999a6e6877f09646d981755-942x1674.webp?w=960&fm=webp&q=75 960w",
          "alt": "Burma Teak Door",
          "w": 942,
          "h": 1674
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "burma-border-teak-door",
    "name": "Burma Border Teak Door",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Border teak build with the classic teak face",
    "specs": [
      "Burma-border teak sections",
      "Solid panel or glazed layouts",
      "Seasoned to resist warping",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/0683b23fe78fceb36c77033757bcdb56fb0fc50d-867x1156.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/0683b23fe78fceb36c77033757bcdb56fb0fc50d-867x1156.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/0683b23fe78fceb36c77033757bcdb56fb0fc50d-867x1156.webp?w=960&fm=webp&q=75 960w",
        "alt": "Burma Border Teak Door",
        "w": 867,
        "h": 1156
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/ec2455a2757250f8b2a83ef5fea38c0b641e76d0-926x1540.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/ec2455a2757250f8b2a83ef5fea38c0b641e76d0-926x1540.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/ec2455a2757250f8b2a83ef5fea38c0b641e76d0-926x1540.webp?w=960&fm=webp&q=75 960w",
          "alt": "Burma Border Teak Door",
          "w": 926,
          "h": 1540
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "teak-osc-2nds",
    "name": "2nds Teak OSC Doors",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "One-side-clear teak seconds — real teak, real value",
    "specs": [
      "One side clear (OSC) teak grade",
      "Minor natural marks on reverse face",
      "The economical way into solid teak",
      "Limited stock, per-piece pricing"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/913c6952d4b21f38e7eccce8e79699458c21d2af-960x1707.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/913c6952d4b21f38e7eccce8e79699458c21d2af-960x1707.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/913c6952d4b21f38e7eccce8e79699458c21d2af-960x1707.webp?w=960&fm=webp&q=75 960w",
        "alt": "2nds Teak OSC Doors",
        "w": 960,
        "h": 1707
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/27b4fb3cb38557cfb32afad3047315f2a6e3e5b5-960x1707.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/27b4fb3cb38557cfb32afad3047315f2a6e3e5b5-960x1707.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/27b4fb3cb38557cfb32afad3047315f2a6e3e5b5-960x1707.webp?w=960&fm=webp&q=75 960w",
          "alt": "2nds Teak OSC Doors",
          "w": 960,
          "h": 1707
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "gana-teak-polish-door",
    "name": "Gana Teak Polish Doors",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Ghana teak, delivered pre-polished and ready to hang",
    "specs": [
      "Ghana teak, factory polish finish",
      "No on-site polishing needed",
      "Consistent sheen across the leaf",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/02d24528f2f9e76573c005622f90afdb0178ef77-643x1080.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/02d24528f2f9e76573c005622f90afdb0178ef77-643x1080.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/02d24528f2f9e76573c005622f90afdb0178ef77-643x1080.webp?w=960&fm=webp&q=75 960w",
        "alt": "Gana Teak Polish Doors",
        "w": 643,
        "h": 1080
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/de5650f9edb3d91600a6e090003214651fecf349-960x960.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/de5650f9edb3d91600a6e090003214651fecf349-960x960.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/de5650f9edb3d91600a6e090003214651fecf349-960x960.webp?w=960&fm=webp&q=75 960w",
          "alt": "Gana Teak Polish Doors",
          "w": 960,
          "h": 960
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "architect-teak-door",
    "name": "Architect Teak Doors",
    "world": "doors",
    "sub": "Teak Doors",
    "tag": "Architect-spec teak doors built to drawing",
    "specs": [
      "Built to architect drawings & sections",
      "Custom panels, glazing & grooves",
      "Site-matched polish samples",
      "Project & bulk friendly"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/4507ce5f3845a36ef1338097e9a889208869b27d-768x1361.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/4507ce5f3845a36ef1338097e9a889208869b27d-768x1361.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/4507ce5f3845a36ef1338097e9a889208869b27d-768x1361.webp?w=960&fm=webp&q=75 960w",
        "alt": "Architect Teak Doors",
        "w": 768,
        "h": 1361
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/cad595cee265ecac21623985bc74fc72559f804a-693x1280.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/cad595cee265ecac21623985bc74fc72559f804a-693x1280.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/cad595cee265ecac21623985bc74fc72559f804a-693x1280.webp?w=960&fm=webp&q=75 960w",
          "alt": "Architect Teak Doors",
          "w": 693,
          "h": 1280
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/1eba6e7ed70034c24af2e80ff4e3d5e55f327c72-960x960.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/1eba6e7ed70034c24af2e80ff4e3d5e55f327c72-960x960.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/1eba6e7ed70034c24af2e80ff4e3d5e55f327c72-960x960.webp?w=960&fm=webp&q=75 960w",
          "alt": "Architect Teak Doors",
          "w": 960,
          "h": 960
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/f1d01398545cfe5fe22dc2feef826afb223944e5-960x1707.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/f1d01398545cfe5fe22dc2feef826afb223944e5-960x1707.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/f1d01398545cfe5fe22dc2feef826afb223944e5-960x1707.webp?w=960&fm=webp&q=75 960w",
          "alt": "Architect Teak Doors",
          "w": 960,
          "h": 1707
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "veneer-designer-door",
    "name": "Veneer Designer Doors",
    "world": "doors",
    "sub": "Veneer Doors",
    "tag": "Natural veneer faces in designer layouts",
    "specs": [
      "Natural wood veneer skins",
      "Designer groove & inlay patterns",
      "Solid engineered core",
      "Polish or PU finish options"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/9867f063113708d27c02d8cce0daa580322487fc-960x1333.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/9867f063113708d27c02d8cce0daa580322487fc-960x1333.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/9867f063113708d27c02d8cce0daa580322487fc-960x1333.webp?w=960&fm=webp&q=75 960w",
        "alt": "Veneer Designer Doors",
        "w": 960,
        "h": 1333
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/f3cd6e36ffd3209a9a058df5df96cc1c332da570-960x1440.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/f3cd6e36ffd3209a9a058df5df96cc1c332da570-960x1440.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/f3cd6e36ffd3209a9a058df5df96cc1c332da570-960x1440.webp?w=960&fm=webp&q=75 960w",
          "alt": "Veneer Designer Doors",
          "w": 960,
          "h": 1440
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "veneer-cng-door",
    "name": "Veneer CNG Doors",
    "world": "doors",
    "sub": "Veneer Doors",
    "tag": "CNC-carved grooves through natural veneer",
    "specs": [
      "CNC-routed face patterns",
      "Natural veneer over solid core",
      "Crisp, repeatable detailing",
      "Made to your frame size"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/938ce5c7bea9bd791c09253d0de33af83ebfdbcc-800x1200.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/938ce5c7bea9bd791c09253d0de33af83ebfdbcc-800x1200.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/938ce5c7bea9bd791c09253d0de33af83ebfdbcc-800x1200.webp?w=960&fm=webp&q=75 960w",
        "alt": "Veneer CNG Doors",
        "w": 800,
        "h": 1200
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/eab29100c473104c40a2558ca27da26b9f69206a-640x640.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/eab29100c473104c40a2558ca27da26b9f69206a-640x640.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/eab29100c473104c40a2558ca27da26b9f69206a-640x640.webp?w=960&fm=webp&q=75 960w",
          "alt": "Veneer CNG Doors",
          "w": 640,
          "h": 640
        },
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/dc1fdcfb72ef08b3516512227cfaf425aaefaf22-271x500.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/dc1fdcfb72ef08b3516512227cfaf425aaefaf22-271x500.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/dc1fdcfb72ef08b3516512227cfaf425aaefaf22-271x500.webp?w=960&fm=webp&q=75 960w",
          "alt": "Veneer CNG Doors",
          "w": 271,
          "h": 500
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "xlent-710-ply",
    "name": "XLENT 710 Ply",
    "world": "ply",
    "sub": "710 Marine Grade",
    "tag": "Boiling-waterproof 710 for kitchens and bathrooms",
    "specs": [
      "IS:710 BWP marine grade",
      "72-hour boil tested",
      "Kitchens, baths, exteriors",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtron-club-prime-710",
    "name": "XTRON CLUB PRIME 710",
    "world": "ply",
    "sub": "710 Marine Grade",
    "tag": "Club-grade 710 with hardwood throughout",
    "specs": [
      "IS:710 BWP, full hardwood core",
      "Chemically treated, borer-proof",
      "Heavy-duty furniture & marine use",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtron-signature-710",
    "name": "XTRON SIGNATURE 710",
    "world": "ply",
    "sub": "710 Marine Grade",
    "tag": "The signature sheet — our best core, our best face",
    "specs": [
      "Flagship IS:710 BWP grade",
      "A+ faces both sides",
      "Lifetime warranty programme",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtorq-bb",
    "name": "XTORQ B/B Pine & H/W",
    "world": "ply",
    "sub": "Blockboard",
    "tag": "Pine and hardwood blockboards that stay dead straight",
    "specs": [
      "Seasoned pine / hardwood battens",
      "No sag on long spans",
      "Wardrobe shutters & panels",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtron-calibrated",
    "name": "XTRON Calibrated Ply",
    "world": "ply",
    "sub": "Calibrated",
    "tag": "Machine-calibrated thickness for flawless laminates",
    "specs": [
      "European calibration line",
      "±0.2 mm thickness tolerance",
      "Zero undulation under laminate",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xtreme-ply",
    "name": "XTREME Ply & B/B",
    "world": "ply",
    "sub": "Plywood",
    "tag": "Flagship ply and blockboard for hard-working interiors",
    "specs": [
      "Plywood + blockboard range",
      "Dense, gap-free core",
      "Uniform thickness, low warp",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xplor-ply",
    "name": "XPLOR Ply",
    "world": "ply",
    "sub": "Plywood",
    "tag": "Dependable commercial ply for everyday furniture",
    "specs": [
      "Commercial MR grade",
      "Smooth calibrated faces",
      "Furniture & panelling",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "xlent-ply",
    "name": "XLENT Ply",
    "world": "ply",
    "sub": "Plywood",
    "tag": "Step-up ply with tighter cores and cleaner faces",
    "specs": [
      "Premium MR grade",
      "Screw-holding certified",
      "Kitchens & wardrobes",
      "Standard 8′×4′ sheets"
    ],
    "visual": {
      "kind": "material",
      "material": "ply",
      "base": "#C9AE85",
      "dark": "#8A7355",
      "light": "#E2CDA8"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  },
  {
    "id": "mahagony",
    "name": "Mahagony Wood",
    "world": "timbers",
    "sub": "Hardwood & Neem",
    "tag": "Deep reddish-brown, fine grain — furniture royalty",
    "specs": [
      "Plantation mahogany, kiln-dried",
      "Fine, even grain — carves & polishes well",
      "Furniture, panelling, doors",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#6E3F30",
      "dark": "#553025",
      "light": "#84503E"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "neem-premium",
    "name": "Neem Premium",
    "world": "timbers",
    "sub": "Hardwood & Neem",
    "tag": "Naturally pest-resistant, select grade",
    "specs": [
      "Select-grade seasoned neem",
      "Naturally insect-repellent timber",
      "Doors, frames & shelving",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8F7350",
      "dark": "#71593D",
      "light": "#A58862"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "neem-regular",
    "name": "Neem Regular",
    "world": "timbers",
    "sub": "Hardwood & Neem",
    "tag": "Honest, economical hardwood for everyday work",
    "specs": [
      "Standard-grade seasoned neem",
      "Economical all-rounder",
      "Utility doors & frames",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#977C59",
      "dark": "#796244",
      "light": "#AC916B"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "australian-honne",
    "name": "Australian Honne Wood",
    "world": "timbers",
    "sub": "Honne",
    "tag": "Dense reddish hardwood — takes polish beautifully",
    "specs": [
      "Imported Australian honne",
      "High density, excellent screw-holding",
      "Doors, frames & heavy sections",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8B5A3C",
      "dark": "#6F4730",
      "light": "#A26C49"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "malaysian-honne",
    "name": "Malaysian Honne Wood",
    "world": "timbers",
    "sub": "Honne",
    "tag": "Workhorse hardwood for frames and structure",
    "specs": [
      "Malaysian honne (kapur family)",
      "Uniform texture, easy to machine",
      "Frames, beams & windows",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#96654A",
      "dark": "#79513B",
      "light": "#AC785A"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "redsal",
    "name": "Redsal Wood",
    "world": "timbers",
    "sub": "Sal",
    "tag": "Load-bearing red sal — the builder’s hardwood",
    "specs": [
      "Seasoned red sal",
      "Very high strength & durability",
      "Structural work, frames, rafters",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#7A4A3A",
      "dark": "#61392D",
      "light": "#8F5B48"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "whitesal",
    "name": "Whitesal Wood",
    "world": "timbers",
    "sub": "Sal",
    "tag": "Light-toned sal for frames and utility work",
    "specs": [
      "Seasoned white sal",
      "Straight sections, economical",
      "Frames & general construction",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#A98F6B",
      "dark": "#8A7355",
      "light": "#BFA57E"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "burmese-teak",
    "name": "Burmese Teak",
    "world": "timbers",
    "sub": "Teak",
    "tag": "The benchmark — tight grain, natural oils, decades of life",
    "specs": [
      "Imported Burma teak logs, sawn in-house",
      "High natural oil content — termite & rot resistant",
      "Ideal for main doors, frames & carving",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8A6845",
      "dark": "#6E5236",
      "light": "#A57F55"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "burma-border-teak",
    "name": "Burma Border Teak",
    "world": "timbers",
    "sub": "Teak",
    "tag": "Border-grade Burma teak — the classic look, keener price",
    "specs": [
      "Burma-border teak, graded and seasoned",
      "Straight grain, warm golden tone",
      "Doors, frames, windows & furniture",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#8F6C46",
      "dark": "#725638",
      "light": "#A88255"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "gana-teak",
    "name": "Gana Teak Wood",
    "world": "timbers",
    "sub": "Teak",
    "tag": "African teak with bold figure — strong and stable",
    "specs": [
      "Ghana teak, kiln-seasoned",
      "Pronounced grain figure",
      "Good stability across seasons",
      "Sold per cubic foot, cut to order"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#96754C",
      "dark": "#785C3B",
      "light": "#AD8A5C"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "commercial-teak",
    "name": "Commercial Teak Wood",
    "world": "timbers",
    "sub": "Teak",
    "tag": "Everyday teak for frames and general woodwork",
    "specs": [
      "Budget-friendly teak grade",
      "Frames, shutters & general carpentry",
      "Machined to your sizes",
      "Sold per cubic foot"
    ],
    "visual": {
      "kind": "material",
      "material": "timber",
      "base": "#9C7B52",
      "dark": "#7E6240",
      "light": "#B29063"
    },
    "purchasable": false,
    "priceUnit": "cft"
  },
  {
    "id": "wpc-cnc-door",
    "name": "28 mm CNC WPC Doors",
    "world": "wpc",
    "sub": "WPC Doors",
    "tag": "CNC-carved WPC doors — zero swelling, ever",
    "specs": [
      "28 mm solid WPC leaf",
      "CNC-carved face designs",
      "Bathroom & utility safe — 100% waterproof",
      "Paint or PU finish options"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/68731cb18e478e1e2e44f78646e4964ce60369c3-645x1201.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/68731cb18e478e1e2e44f78646e4964ce60369c3-645x1201.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/68731cb18e478e1e2e44f78646e4964ce60369c3-645x1201.webp?w=960&fm=webp&q=75 960w",
        "alt": "28 mm CNC WPC Doors",
        "w": 645,
        "h": 1201
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/0ce8ba4ff8aed1721d9ad320c646285cc3d8d37c-960x1438.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/0ce8ba4ff8aed1721d9ad320c646285cc3d8d37c-960x1438.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/0ce8ba4ff8aed1721d9ad320c646285cc3d8d37c-960x1438.webp?w=960&fm=webp&q=75 960w",
          "alt": "28 mm CNC WPC Doors",
          "w": 960,
          "h": 1438
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "wpc-digital-veneer-door",
    "name": "Digital Veneer WPC Doors",
    "world": "wpc",
    "sub": "WPC Doors",
    "tag": "28 & 30 mm WPC with photo-real digital veneer faces",
    "specs": [
      "28 mm & 30 mm leaves",
      "Digital-printed veneer textures",
      "Waterproof core, UV-stable print",
      "Wood looks without wood worries"
    ],
    "visual": {
      "kind": "photo",
      "cover": {
        "src": "https://cdn.sanity.io/images/sn4590lo/production/5652cfcec3c4339a95b7000c788c347cf91cdba6-960x1440.webp?w=480&fm=webp&q=75",
        "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/5652cfcec3c4339a95b7000c788c347cf91cdba6-960x1440.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/5652cfcec3c4339a95b7000c788c347cf91cdba6-960x1440.webp?w=960&fm=webp&q=75 960w",
        "alt": "Digital Veneer WPC Doors",
        "w": 960,
        "h": 1440
      },
      "gallery": [
        {
          "src": "https://cdn.sanity.io/images/sn4590lo/production/4b2b971b364ebaef413d2cd0cc163ee11856f1a2-960x1615.webp?w=480&fm=webp&q=75",
          "srcSet": "https://cdn.sanity.io/images/sn4590lo/production/4b2b971b364ebaef413d2cd0cc163ee11856f1a2-960x1615.webp?w=480&fm=webp&q=75 480w, https://cdn.sanity.io/images/sn4590lo/production/4b2b971b364ebaef413d2cd0cc163ee11856f1a2-960x1615.webp?w=960&fm=webp&q=75 960w",
          "alt": "Digital Veneer WPC Doors",
          "w": 960,
          "h": 1615
        }
      ]
    },
    "purchasable": false,
    "priceUnit": "leaf"
  },
  {
    "id": "wpc-sheets",
    "name": "WPC Solid Sheets",
    "world": "wpc",
    "sub": "WPC Sheets",
    "tag": "100% waterproof boards — 6 mm to 18 mm, two densities",
    "specs": [
      "Thicknesses: 18 / 16 / 12 / 8 / 6 mm",
      "Densities: 0.45 & 0.55",
      "Waterproof, termite-proof, fire-retardant",
      "Screws, routs & paints like wood"
    ],
    "visual": {
      "kind": "material",
      "material": "wpc",
      "base": "#B8C4C0",
      "dark": "#7E8F8A",
      "light": "#DDE5E2"
    },
    "purchasable": false,
    "priceUnit": "sheet"
  }
]
