/**
 * GENERATED by scripts/fetch-catalog.mjs — do not edit by hand.
 * No SANITY_PROJECT_ID configured — site uses local data only.
 */
import type { Product } from './products'

export const CMS_PRODUCTS: Product[] = []
