/**
 * GENERATED by scripts/build-leaves.mjs — do not edit by hand.
 *
 * The door leaf cut out of each catalogue photograph and squared up: no wall,
 * no architrave, no camera tilt. This is the only image "see it in your
 * doorway" can warp into a customer's photo. Corners are marked by hand in
 * photoMap.ts; run `npm run leaves:build` after changing one.
 *
 * `w`/`h` are the generated leaf's own pixels, and their ratio is the door's
 * *true* proportions rather than the foreshortened ones in the photo — which
 * is what stops an angled shot from arriving in the doorway stretched.
 */
export interface LeafImage {
  src: string
  w: number
  h: number
}

export const LEAF_IMAGES: Record<string, LeafImage> = {
  'burma-teak-door': { src: '/images/leaves/burma-teak-door.webp', w: 489, h: 1200 }, // main-04, frontal
  'burma-border-teak-door': { src: '/images/leaves/burma-border-teak-door.webp', w: 594, h: 1200 }, // main-25, frontal
  'teak-osc-2nds': { src: '/images/leaves/teak-osc-2nds.webp', w: 543, h: 1200 }, // main-41, frontal
  'gana-teak-polish-door': { src: '/images/leaves/gana-teak-polish-door.webp', w: 622, h: 1200 }, // main-09, frontal
  'architect-teak-door': { src: '/images/leaves/architect-teak-door.webp', w: 613, h: 1200 }, // main-34, frontal
  'honne-ab-door': { src: '/images/leaves/honne-ab-door.webp', w: 596, h: 1200 }, // main-27, frontal
  'mahagony-ab-door': { src: '/images/leaves/mahagony-ab-door.webp', w: 553, h: 1200 }, // main-16, frontal
  'veneer-designer-door': { src: '/images/leaves/veneer-designer-door.webp', w: 527, h: 1200 }, // room-03, frontal
  'veneer-cng-door': { src: '/images/leaves/veneer-cng-door.webp', w: 680, h: 1200 }, // main-11, frontal
  'laminate-cng-door': { src: '/images/leaves/laminate-cng-door.webp', w: 455, h: 1200 }, // room-31, frontal
  'laminate-designer-door': { src: '/images/leaves/laminate-designer-door.webp', w: 512, h: 1200 }, // room-20, frontal
  'microcoat-door': { src: '/images/leaves/microcoat-door.webp', w: 606, h: 1200 }, // room-44, frontal
  'primer-door': { src: '/images/leaves/primer-door.webp', w: 525, h: 1200 }, // room-10, frontal
  'korean-membrane-door': { src: '/images/leaves/korean-membrane-door.webp', w: 540, h: 1200 }, // room-30, frontal
  'membrane-door': { src: '/images/leaves/membrane-door.webp', w: 522, h: 1200 }, // room-33, frontal
  'wpc-cnc-door': { src: '/images/leaves/wpc-cnc-door.webp', w: 532, h: 1200 }, // room-25, frontal
  'wpc-digital-veneer-door': { src: '/images/leaves/wpc-digital-veneer-door.webp', w: 363, h: 1200 }, // main-03, frontal
}
